# Generated by Django 3.2.5 on 2022-05-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20220525_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('Student', 'Student '), ('Employee', 'Employee')], default='employee', max_length=20, null=True),
        ),
    ]
